name: Playwright Tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag bookpitch
#      - name: Containerized Build
#        uses:  ./.github/actions/
      - name: Install dependencies
        run: npm ci
      - name: Run migrations
        run: npx prisma db push
      - name: Start the app
        run: npm run dev &
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test tests/screenshot
        env:
          NEXT_PUBLIC_URL: http://localhost:3000
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
